### PR TITLE
Rewrite Links to resolve markdown links correctly

### PR DESCRIPTION
**Pull request by RyanGreenup**
This change allows links to be followed in the server.

Before this change, following a markdown link in in the browser, e.g. `uni.md`, would result in the url:

- http://127.0.0.1:36939/university.md

which does not open the file to be previewed, this change rewrites the url to redirect to:

- http://127.0.0.1:36939/?path=university.md

Which allows the links to be followed in the browser.

This means the program can be used as a simple server for a zettelkasten.

### CODE REVIEW

**Comment by elijah-potter** [comment]
Wow, that isn't something I thought of. Thanks for the pull request!

**Comment by elijah-potter** [comment]
On second thought, is it important that these links be resolved relative to the referring file? Right now they are being resolved relative to the Tatum working directory.

**Comment by RyanGreenup** [comment]
Yeah I considered this too. 

Right now this assumes files from root similar to, eg WikiJS. 

If I get time in the next day or so I can PR relative paths which would work for directories?

This would require an additional crate for relpath though.

**Comment by elijah-potter** [comment]
If you're willing to get that up and running, that'd be great! Let me know if there's anything I can do to help.

**Comment by RyanGreenup** [comment]
I opened up PR #2, let me know what you think.

**Pull request merged**
